# Generated by Django 5.2.5 on 2025-08-18 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Id', primary_key=True, serialize=False),
        ),
    ]
