# Generated by Django 5.2.5 on 2025-08-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of bullet features shown in card'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('service', 'Per Service'), ('week', 'Per Week'), ('project', 'Per Project')], default='service', help_text='How the base price is shown on the site (e.g. /hour, /service)', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating 0.00 - 5.00', max_digits=3),
        ),
        migrations.AddField(
            model_name='service',
            name='response_level',
            field=models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('routine', 'Routine'), ('seasonal', 'Seasonal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Estimated onsite duration for scheduling'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seasonal_availability',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], help_text='Season when this service is primarily offered', max_length=10, null=True),
        ),
    ]
