# Generated by Django 5.2.7 on 2025-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_available_24_7_service_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='services/'),
        ),
    ]
