# Generated by Django 5.2.5 on 2025-08-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True, verbose_name='date of birth'),
        ),
    ]
