# Generated by Django 5.2.7 on 2025-10-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_email_verification_codes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='email_verif_user_id_369f6b_idx',
            old_name='email_ver_user_id_b00bd7_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='email_verif_token_d1ad36_idx',
            old_name='email_ver_token_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='email_verif_created_028ca8_idx',
            old_name='email_ver_created_idx',
        ),
    ]
