# Generated by Django 5.2.5 on 2025-08-18 16:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_rename_property_propertynote_property_ref_and_more'),
        ('services', '0002_alter_service_id'),
        ('users', '0002_alter_userprofile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('code', models.CharField(help_text='Unique promotion code', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Promotion code must contain only uppercase letters, numbers, hyphens, and underscores', regex='^[A-Z0-9_-]+$')])),
                ('name', models.CharField(help_text='Promotion name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Promotion description', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(help_text='Promotion start date')),
                ('valid_until', models.DateTimeField(help_text='Promotion end date')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this promotion can be used (null = unlimited)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this promotion has been used')),
                ('usage_limit_per_customer', models.PositiveIntegerField(blank=True, help_text='Maximum uses per customer (null = unlimited)', null=True)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quote amount required', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this promotion currently active?')),
                ('for_new_customers_only', models.BooleanField(default=False, help_text='Only applicable to new customers?')),
                ('for_existing_customers_only', models.BooleanField(default=False, help_text='Only applicable to existing customers?')),
                ('applicable_services', models.ManyToManyField(blank=True, help_text='Services this promotion applies to (empty = all)', related_name='promotions', to='services.service')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes visible to customer', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff only', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('quote_number', models.CharField(editable=False, help_text='Unique quote number', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Quote title/subject', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of work to be done', null=True)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('processed', 'Processed'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='initialized', help_text='Current quote status', max_length=30)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the quote was processed by staff', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Quote expiration date', null=True)),
                ('customer_response_at', models.DateTimeField(blank=True, help_text='When customer responded (confirmed/rejected)', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before discounts and tax', max_digits=10)),
                ('promotion_code', models.CharField(blank=True, help_text='Applied promotion code', max_length=50, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Tax rate (e.g., 0.075 for 7.5%)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total quote amount', max_digits=10)),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions', null=True)),
                ('customer_notified', models.BooleanField(default=False, help_text='Has customer been notified?')),
                ('customer_notified_at', models.DateTimeField(blank=True, help_text='When customer was notified', null=True)),
                ('viewed_by_customer', models.BooleanField(default=False, help_text='Has customer viewed the quote?')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer first viewed the quote', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer requesting the quote', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='users.userprofile')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff member processing the quote', limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_quotes', to='users.userprofile')),
                ('promotion', models.ForeignKey(blank=True, help_text='Applied promotion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quotes.promotion')),
                ('property_ref', models.ForeignKey(blank=True, help_text='Property for the quote (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('item_type', models.CharField(choices=[('service', 'Service'), ('material', 'Material/Part'), ('labor', 'Labor'), ('other', 'Other')], default='service', help_text='Type of item', max_length=20)),
                ('description', models.CharField(help_text='Item description', max_length=500)),
                ('detailed_description', models.TextField(blank=True, help_text='Detailed description of the item', null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total price (quantity × unit_price)', max_digits=10)),
                ('is_optional', models.BooleanField(default=False, help_text='Is this an optional item?')),
                ('is_included', models.BooleanField(default=True, help_text='Is this item included in the total?')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in quote')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(help_text='Parent quote', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
                ('service', models.ForeignKey(blank=True, help_text='Service being quoted (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='services.service')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote Item',
                'verbose_name_plural': 'Quote Items',
                'db_table': 'quote_items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='promotions_code_893bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['valid_from', 'valid_until'], name='promotions_valid_f_7ffd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='promotions_is_acti_5031c3_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='quotes_quote_n_a300f2_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer', 'status'], name='quotes_custome_cc5ace_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'created_at'], name='quotes_status_bc5df1_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['valid_until'], name='quotes_valid_u_b76eec_idx'),
        ),
    ]
