# Generated by Django 5.2.5 on 2025-08-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('initialized', 'Initialized'), ('processed', 'Processed'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='initialized', help_text='Current quote status', max_length=30),
        ),
    ]
