# Generated by Django 5.2.7 on 2025-10-29 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_property_propertynote_property_ref_and_more'),
        ('quotes', '0002_alter_quote_status'),
        ('users', '0003_userprofile_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email when no account is associated', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='contact_first_name',
            field=models.CharField(blank=True, help_text='First name provided for guest contact', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='contact_last_name',
            field=models.CharField(blank=True, help_text='Last name provided for guest contact', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone provided for guest contact', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer requesting the quote', limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['contact_email'], name='quotes_contact_2f0277_idx'),
        ),
    ]
