# Generated by Django 5.2.7 on 2025-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_rename_awaiting_confirmation_to_awaiting_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('initialized', 'Initialized'), ('processed', 'Processed'), ('awaiting_payment', 'Awaiting Payment'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='initialized', help_text='Current quote status', max_length=30),
        ),
    ]
