# Generated by Django 5.2.7 on 2025-10-31 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('quotes', '0006_alter_quote_status_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='applicable_services',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='quote',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='Applied promotion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='promotions.promotion'),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
