# Generated by Django 5.2.7 on 2025-10-31 12:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_alter_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('code', models.CharField(help_text='Unique promotion code', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Promotion code must contain only uppercase letters, numbers, hyphens, and underscores', regex='^[A-Z0-9_-]+$')])),
                ('name', models.CharField(help_text='Promotion name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Promotion description', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(help_text='Promotion start date')),
                ('valid_until', models.DateTimeField(help_text='Promotion end date')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this promotion can be used (null = unlimited)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this promotion has been used')),
                ('usage_limit_per_customer', models.PositiveIntegerField(blank=True, help_text='Maximum uses per customer (null = unlimited)', null=True)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quote amount required', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this promotion currently active?')),
                ('for_new_customers_only', models.BooleanField(default=False, help_text='Only applicable to new customers?')),
                ('for_existing_customers_only', models.BooleanField(default=False, help_text='Only applicable to existing customers?')),
                ('applicable_services', models.ManyToManyField(blank=True, help_text='Services this promotion applies to (empty = all)', related_name='promotions', to='services.service')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='promotions_code_893bd9_idx'), models.Index(fields=['valid_from', 'valid_until'], name='promotions_valid_f_7ffd1e_idx'), models.Index(fields=['is_active'], name='promotions_is_acti_5031c3_idx')],
            },
        ),
    ]
