# Generated by Django 5.2.5 on 2025-08-16 01:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True, help_text='Check-in timestamp')),
                ('check_in_location', models.JSONField(default=dict, help_text='GPS coordinates of check-in')),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Check-out timestamp', null=True)),
                ('check_out_location', models.JSONField(blank=True, default=dict, help_text='GPS coordinates of check-out')),
                ('mileage', models.DecimalField(blank=True, decimal_places=1, help_text='Travel mileage for this appointment', max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Appointment Check-In',
                'verbose_name_plural': 'Appointment Check-Ins',
                'db_table': 'appointment_check_ins',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='RecurringAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='weekly', help_text='Frequency of service', max_length=20)),
                ('day_of_week', models.PositiveIntegerField(blank=True, help_text='Day of week (0=Monday, 6=Sunday)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month for monthly service', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('preferred_time', models.TimeField(help_text='Preferred time for service')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('start_date', models.DateField(help_text='When recurring schedule starts')),
                ('end_date', models.DateField(blank=True, help_text='When recurring schedule ends (null = ongoing)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this recurring schedule active?')),
                ('last_generated_date', models.DateField(blank=True, help_text='Last date appointments were generated up to', null=True)),
                ('total_appointments_created', models.PositiveIntegerField(default=0, help_text='Total appointments created from this schedule')),
                ('auto_confirm', models.BooleanField(default=True, help_text='Automatically confirm generated appointments')),
                ('skip_holidays', models.BooleanField(default=True, help_text='Skip appointments on holidays')),
            ],
            options={
                'verbose_name': 'Recurring Appointment',
                'verbose_name_plural': 'Recurring Appointments',
                'db_table': 'recurring_appointments',
                'ordering': ['property', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes visible to customer', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff only', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('scheduled_date', models.DateTimeField(help_text='Scheduled appointment start time')),
                ('scheduled_end_time', models.DateTimeField(blank=True, help_text='Scheduled appointment end time', null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='Actual start time of service', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='Actual end time of service', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', help_text='Current appointment status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', help_text='Appointment priority', max_length=20)),
                ('confirmation_code', models.CharField(editable=False, help_text='Unique confirmation code', max_length=20, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When appointment was confirmed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When appointment was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('reschedule_count', models.PositiveIntegerField(default=0, help_text='Number of times this appointment has been rescheduled')),
                ('completion_notes', models.TextField(blank=True, help_text='Notes from service completion', null=True)),
                ('issues_found', models.JSONField(blank=True, default=list, help_text='Issues discovered during service')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Technician recommendations')),
                ('before_photos', models.JSONField(blank=True, default=list, help_text='URLs of before service photos')),
                ('after_photos', models.JSONField(blank=True, default=list, help_text='URLs of after service photos')),
                ('customer_signature', models.TextField(blank=True, help_text='Customer signature (base64 encoded)', null=True)),
                ('customer_feedback', models.TextField(blank=True, help_text='Customer feedback after service', null=True)),
                ('customer_rating', models.PositiveIntegerField(blank=True, help_text='Customer rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base service price', max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional charges (parts, extra services, etc.)', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount applied', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount charged', max_digits=10)),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this part of a recurring schedule?')),
                ('requires_follow_up', models.BooleanField(default=False, help_text='Does this appointment require follow-up?')),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended follow-up date', null=True)),
                ('weather_conditions', models.CharField(blank=True, help_text='Weather conditions during service', max_length=50, null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Has reminder been sent?')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When reminder was sent', null=True)),
                ('additional_services', models.ManyToManyField(blank=True, help_text='Additional services to be performed', related_name='additional_appointments', to='services.service')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Who cancelled the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to='users.userprofile')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Who confirmed the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to='users.userprofile')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who requested the appointment', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointments', to='users.userprofile')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['scheduled_date', 'priority'],
            },
        ),
    ]
