# Generated by Django 5.2.5 on 2025-08-16 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('properties', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='property',
            field=models.ForeignKey(help_text='Property to be serviced', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.property'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, help_text='Original appointment if this is a reschedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(help_text='Primary service to be performed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Assigned technician', limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_appointments', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentcheckin',
            name='appointment',
            field=models.ForeignKey(help_text='Associated appointment', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentcheckin',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentcheckin',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentcheckin',
            name='technician',
            field=models.ForeignKey(help_text='Technician checking in', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='appointmentcheckin',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringappointment',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, help_text='Preferred technician for service', limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recurring_appointments', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='recurringappointment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringappointment',
            name='customer',
            field=models.ForeignKey(help_text='Customer for recurring service', limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_appointments', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='recurringappointment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringappointment',
            name='property',
            field=models.ForeignKey(help_text='Property for recurring service', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_appointments', to='properties.property'),
        ),
        migrations.AddField(
            model_name='recurringappointment',
            name='service',
            field=models.ForeignKey(help_text='Service to be performed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_appointments', to='services.service'),
        ),
        migrations.AddField(
            model_name='recurringappointment',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurring_appointment',
            field=models.ForeignKey(blank=True, help_text='Associated recurring appointment schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.recurringappointment'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date', 'status'], name='appointment_schedul_a4acc9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'scheduled_date'], name='appointment_custome_4293f6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['technician', 'scheduled_date'], name='appointment_technic_8eeeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['property', 'scheduled_date'], name='appointment_propert_c301d2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['confirmation_code'], name='appointment_confirm_31c43c_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
    ]
