# Generated by Django 5.2.5 on 2025-08-16 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('properties', '0002_rename_property_propertynote_property_ref_and_more'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringappointment',
            options={'ordering': ['property_ref', 'start_date'], 'verbose_name': 'Recurring Appointment', 'verbose_name_plural': 'Recurring Appointments'},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_propert_c301d2_idx',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='property',
            new_name='property_ref',
        ),
        migrations.RenameField(
            model_name='recurringappointment',
            old_name='property',
            new_name='property_ref',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['property_ref', 'scheduled_date'], name='appointment_propert_e5c252_idx'),
        ),
    ]
