# Generated by Django 5.2.5 on 2025-08-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertynote',
            old_name='property',
            new_name='property_ref',
        ),
        migrations.RenameField(
            model_name='propertyphoto',
            old_name='property',
            new_name='property_ref',
        ),
    ]
